### ISSUE TITLE
msgpack-lite BUFFER_SHORTAGE Errors on 3.1.0

### ISSUE THREAD

**Issue by Seba0917** [socketio/socket.io-redis#182] opened 2017-01-18 08:36 UTC
Hello,

I am facing some troubles with a working code in 2.0.1 that keeps crashing on 3.1.0.
The temporary fix for me is just to downgrade, but I am sure there is a problem lying underneath.

Maybe related to #172 ?

#### index.js

````
var app = require('express')();
var server = require('http').createServer(app);
var io = require('socket.io')(server);
var redis = require("socket.io-redis");
var sticky = require('sticky-session');
io.adapter(redis({host: 'localhost', port:6379}));

sticky.listen(server,3303);

server.once('listening', function(){
    console.log('Sticky server listening to 3303')
})
````

#### package.json
````{
  "name": "bugger",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha test"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "express-validator": "^3.1.2",
    "http": "0.0.0",
    "redis": "^2.6.5",
    "socket.io": "^1.7.2",
    "socket.io-redis": "^3.1.0",
    "socketio-sticky-session": "^0.4.2",
    "sticky-session": "^1.1.2",
    "util": "^0.10.3"
  }
}
````

#### result

````
1|index | Sticky server listening to 3303
1|index | Error: BUFFER_SHORTAGE
1|index |     at DecodeBuffer.reserve (/var/www/test/node_modules/msgpack-lite/lib/flex-buffer.js:64:41)
1|index |     at bin_buffer (/var/www/test/node_modules/msgpack-lite/lib/read-format.js:93:23)
1|index |     at /var/www/test/node_modules/msgpack-lite/lib/read-token.js:153:12
1|index |     at decode (/var/www/test/node_modules/msgpack-lite/lib/read-core.js:25:12)
1|index |     at map_to_obj (/var/www/test/node_modules/msgpack-lite/lib/read-format.js:52:12)
1|index |     at /var/www/test/node_modules/msgpack-lite/lib/read-token.js:159:12
1|index |     at decode (/var/www/test/node_modules/msgpack-lite/lib/read-core.js:25:12)
1|index |     at array (/var/www/test/node_modules/msgpack-lite/lib/read-format.js:81:16)
1|index |     at /var/www/test/node_modules/msgpack-lite/lib/read-token.js:159:12
1|index |     at Codec.decode (/var/www/test/node_modules/msgpack-lite/lib/read-core.js:25:12)
````

**Comment by darrachequesne** [comment] 2017-01-18 09:02
Yes, I think this is related to https://github.com/socketio/socket.io-redis/issues/172. `BUFFER_SHORTAGE` errors seem to happen when `msgpack-lite` encounters a buffer that it cannot properly decode.

Can you provide a complete test case reproducing the issue?

**Comment by Seba0917** [comment] 2017-01-19 08:33
Hello,

The "working" sample is available here : https://github.com/Seba0917/socket.io-redis-buffer-shortage

**Comment by darrachequesne** [comment] 2017-01-19 15:10
I'm afraid I'm not able to reproduce:
```bash
damien@laptop:~/git$ git clone git@github.com:Seba0917/socket.io-redis-buffer-shortage.git
Cloning into 'socket.io-redis-buffer-shortage'...
remote: Counting objects: 14, done.
remote: Compressing objects: 100% (13/13), done.
Receiving objects: 100% (14/14), done.
Resolving deltas: 100% (4/4), done.
remote: Total 14 (delta 4), reused 0 (delta 0), pack-reused 0
Checking connectivity... done.
damien@laptop:~/git$ cd socket.io-redis-buffer-shortage/
damien@laptop:~/git/socket.io-redis-buffer-shortage$ npm i
test@1.0.0 /home/damien/git/socket.io-redis-buffer-shortage
├─┬ express@4.14.0 
│ ├─┬ accepts@1.3.3 
│ │ ├─┬ mime-types@2.1.14 
│ │ │ └── mime-db@1.26.0 
│ │ └── negotiator@0.6.1 
│ ├── array-flatten@1.1.1 
│ ├── content-disposition@0.5.1 
│ ├── content-type@1.0.2 
│ ├── cookie@0.3.1 
│ ├── cookie-signature@1.0.6 
│ ├─┬ debug@2.2.0 
│ │ └── ms@0.7.1 
│ ├── depd@1.1.0 
│ ├── encodeurl@1.0.1 
│ ├── escape-html@1.0.3 
│ ├── etag@1.7.0 
│ ├─┬ finalhandler@0.5.0 
│ │ ├── statuses@1.3.1 
│ │ └── unpipe@1.0.0 
│ ├── fresh@0.3.0 
│ ├── merge-descriptors@1.0.1 
│ ├── methods@1.1.2 
│ ├─┬ on-finished@2.3.0 
│ │ └── ee-first@1.1.1 
│ ├── parseurl@1.3.1 
│ ├── path-to-regexp@0.1.7 
│ ├─┬ proxy-addr@1.1.3 
│ │ ├── forwarded@0.1.0 
│ │ └── ipaddr.js@1.2.0 
│ ├── qs@6.2.0 
│ ├── range-parser@1.2.0 
│ ├─┬ send@0.14.1 
│ │ ├── destroy@1.0.4 
│ │ ├─┬ http-errors@1.5.1 
│ │ │ ├── inherits@2.0.3 
│ │ │ └── setprototypeof@1.0.2 
│ │ └── mime@1.3.4 
│ ├── serve-static@1.11.1 
│ ├─┬ type-is@1.6.14 
│ │ └── media-typer@0.3.0 
│ ├── utils-merge@1.0.0 
│ └── vary@1.1.0 
├── http@0.0.0 
├─┬ socket.io@1.7.2 
│ ├─┬ debug@2.3.3 
│ │ └── ms@0.7.2 
│ ├─┬ engine.io@1.8.2 
│ │ ├── base64id@1.0.0 
│ │ ├─┬ debug@2.3.3 
│ │ │ └── ms@0.7.2 
│ │ ├─┬ engine.io-parser@1.3.2 
│ │ │ ├── after@0.8.2 
│ │ │ ├── arraybuffer.slice@0.0.6 
│ │ │ ├── base64-arraybuffer@0.1.5 
│ │ │ ├── blob@0.0.4 
│ │ │ └── wtf-8@1.0.0 
│ │ └─┬ ws@1.1.1 
│ │   ├── options@0.0.6 
│ │   └── ultron@1.0.2 
│ ├─┬ has-binary@0.1.7 
│ │ └── isarray@0.0.1 
│ ├── object-assign@4.1.0 
│ ├─┬ socket.io-adapter@0.5.0 
│ │ └─┬ debug@2.3.3 
│ │   └── ms@0.7.2 
│ ├─┬ socket.io-client@1.7.2 
│ │ ├── backo2@1.0.2 
│ │ ├── component-bind@1.0.0 
│ │ ├── component-emitter@1.2.1 
│ │ ├─┬ debug@2.3.3 
│ │ │ └── ms@0.7.2 
│ │ ├─┬ engine.io-client@1.8.2 
│ │ │ ├── component-emitter@1.2.1 
│ │ │ ├── component-inherit@0.0.3 
│ │ │ ├─┬ debug@2.3.3 
│ │ │ │ └── ms@0.7.2 
│ │ │ ├── has-cors@1.1.0 
│ │ │ ├── parsejson@0.0.3 
│ │ │ ├── parseqs@0.0.5 
│ │ │ ├── xmlhttprequest-ssl@1.5.3 
│ │ │ └── yeast@0.1.2 
│ │ ├── indexof@0.0.1 
│ │ ├── object-component@0.0.3 
│ │ ├─┬ parseuri@0.0.5 
│ │ │ └─┬ better-assert@1.0.2 
│ │ │   └── callsite@1.0.0 
│ │ └── to-array@0.1.4 
│ └─┬ socket.io-parser@2.3.1 
│   ├── component-emitter@1.1.2 
│   └── json3@3.3.2 
├─┬ socket.io-redis@3.1.0 
│ ├─┬ async@2.1.4 
│ │ └── lodash@4.17.4 
│ ├─┬ debug@2.3.3 
│ │ └── ms@0.7.2 
│ ├─┬ msgpack-lite@0.1.26 
│ │ ├── event-lite@0.1.1 
│ │ ├── ieee754@1.1.8 
│ │ ├── int64-buffer@0.1.9 
│ │ └── isarray@1.0.0 
│ ├─┬ redis@2.6.3 
│ │ ├── double-ended-queue@2.1.0-0 
│ │ ├── redis-commands@1.3.0 
│ │ └── redis-parser@2.3.0 
│ └── uid2@0.0.3 
└─┬ sticky-session@1.1.2 
  └── ip@1.1.4 

npm WARN test@1.0.0 No repository field.
damien@laptop:~/git/socket.io-redis-buffer-shortage$ docker run --name redis3 -p 6379:6379 -d redis:3
221d869fa5de9a70bc9355dc7dc585692894b065dd4e5003dd5cb87c20477a5a
damien@laptop:~/git/socket.io-redis-buffer-shortage$ node index.js 
Sticky server listening to 3303
```
You didn't provide any client code, are there some extra steps?

**Comment by mavrick** [comment] 2017-01-20 08:34
Have you tried a new redis box with nothing else connected to it?

**Comment by Seba0917** [comment] 2017-01-23 02:55
Interestingly, the code in my repository is enough to make the bug happen with a server running 
`Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=687a2a319020fa42`  (you may have to wait up to 5 seconds) and runs  fine on a `Redis server v=3.2.1 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=8ab9de078b62748e`

Not sure if it is really related to the Redis Server version only as I have tested on two different physical servers. 

Is there a way that I can give you more debugging informations ?

**Comment by darrachequesne** [comment] 2017-05-20 04:56
Closed by https://github.com/socketio/socket.io-redis/pull/218.

**Closed by darrachequesne** 2017-05-20 04:56 UTC
