### ISSUE TITLE
Big memory leak .clients() and .allRooms()

### ISSUE THREAD

**Issue by allthetime** [socketio/socket.io-redis#197] opened 2017-02-07 11:20 UTC
So, I recently rewrote some of our network code to support multiple nodes with the help of this library.

I used `adapter.clients()` and `adapter.allRooms()` only, and in a single place in the code each.

Everything worked just fine in dev, but once I put it into production (thousands of connections) a massive memory leak became apparent.

I spent the better part of today trying to track the leak down thinking it was something to do with the way I wrote the new code. After trying everything, I removed  `adapter.clients()` and `adapter.allRooms()` and instead just used the standard socket.io `.rooms` object to get the channel names and socket ids, losing multi-node functionality, but completely getting rid of the memory leak. I removed the functions one at a time and only after both were gone did the leak disappear.

I'm curious if anyone is using these functions in a high traffic production environment (the functions get called A LOT) successfully, because currently it doesn't seem possible.

I would be interested in looking into this leak further when I have some time, but am not very experienced in tracking down memory leaks, or very knowledgable about the inner workings of this library.

Any insight would be greatly appreciated.

**Comment by artofspeed** [comment] 2017-02-07 22:18
Why did you close it, did you solve it?

**Comment by allthetime** [comment] 2017-02-07 23:02
@artofspeed I just wanted to gather some more evidence, like testing a simplest possible application that displays the problem, and a few more things with my own app before making this claim, at which  point I will reopen it. I'm wary of clogging up 'issues' with what might just be a personal issue.

**Comment by artofspeed** [comment] 2017-02-15 06:58
do you have a simple sample code that can replicate this issue?

**Comment by darrachequesne** [comment] 2017-02-15 08:01
Currently, each Adapter maintains its own list of sockets. When calling `clients` method (or any other one), the requesting Adapter publish a request, and every other Adapter will handle that request by answering / doing something on its own list of sockets. For example, an Adapter receiving a `clients` request will publish its own list of sockets, and the requesting Adapter will concat every response before returning the whole list.

Note: I think it was handled differently in earlier versions, with the list of sockets being stored in Redis directly (and not on the node instance), but I don't remember what triggered the change.

**Comment by allthetime** [comment] 2017-02-15 10:34
@artofspeed simply using those functions, in a minimal fashion, repeatedly is enough to cause the leak.

in my case:

```
adapter.allRooms(function(rooms){
      adapter.clients(rooms, function(clients){
     
           //....

       });
});
```

But just doing adapter.allRooms() will as well.

As soon as I got rid of these functions and used a self made method to collect clients and rooms the leak went away.

**Comment by rhclayto** [comment] 2017-02-17 17:20
I'm writing code right now that uses those functions, but haven't got far enough to consider load testing yet. Has anyone else seen this problem?

@allthetime: Do you have a snippet of your self-made methods?

**Comment by ShadowCoreCom** [comment] 2017-02-21 17:38
io.of('/').adapter.clients(function (err, clients) {
        if (!err && clients.length > 0) {
             
        }
    });


For 2-4k calls it consumes 1GB of memory

**Comment by darrachequesne** [comment] 2017-02-22 06:51
If you heavily rely on those methods, I guess you should store the associations in a Redis Set directly. The only drawback I see is that you have to clean up the set when a node fails.

**Comment by rhclayto** [comment] 2017-02-22 06:54
So what are we talking about here? Is this a leak, memory is consumed & never released, or is it just an expensive function that uses a lot of memory, but releases it back when it's done? I'm not sure from 'For 2-4k calls it consumes 1GB of memory' which one is meant.

**Comment by darrachequesne** [comment] 2017-02-22 06:57
@rhclayto for me it's an expensive function that releases the memory when it's done.

**Comment by ShadowCoreCom** [comment] 2017-02-23 01:19
Memory not realeases. My script grown up from 200m to 2.5gb and than node js crashed. gc.collect() arent help. 
I forgot about this method and used hooks to determine online users between forks. 
I can show you graphics from keymetrics , that show how it leaks memory.

**Comment by webeks** [comment] 2017-03-22 15:17
@ShadowCoreCom would you care to share how your own hooks look like? I'm trying to update from earlier version and its nightmare specially since production is already consuming cca 30GB of memory so I can't afford any additional leaks :)

**Comment by ShadowCoreCom** [comment] 2017-03-23 22:02
@webeks 
Yep

```
    io.of('/').adapter.customHook = function (data, cb) {
        if (data == 'get_online') {
            var srvSockets = io.sockets.sockets;
            // console.log(' wrker ' + cluster.worker.id + ' ' + Object.keys(srvSockets).length);
            cb(Object.keys(srvSockets).length);
        }
    };
```
And then somewhere , where you want to get online use : 

```
                io.of('/').adapter.customRequest('get_online', function(err, replies){
                    var online = 0;
                    for (var i in replies){
                        online += (parseInt(replies[i]) || 0);
                    }
                    redisClient3.set('online', online);
                    STATISTICS.online = online;
                 });
```

**Comment by ShadowCoreCom** [comment] 2017-05-08 17:00
Now i have a problem , sometimes forks sends 0 ( i dont know why) on high load , so online is jumping all time ...

**Comment by darrachequesne** [comment] 2017-05-20 12:40
Again, storing the associations between ids and rooms in Redis is possible and should be (a lot) more efficient that the current version (where a node sends a request and wait for the response of all the other nodes), but there is still an issue about keeping data up-to-date when a node goes down / crashes / is restarted. Anyone has a suggestion?

**Comment by beaucollins** [comment] 2017-06-03 22:15
I'm seeing a memory leak as well now. The `.requests` object within a `Redis` instance is growing unbounded. It looks like there's a codepath that doesn't delete the request.

**Comment by darrachequesne** [comment] 2017-06-04 06:47
https://github.com/socketio/socket.io-redis/pull/225 should fix the issue, could one check with `5.1.0` version?

**Comment by mayfer** [comment] 2017-06-14 13:21
@darrachequesne just tried it on production again.
Huge memory leak persists with 5.1.0 (and socket.io 2.0.1) when using `adapter.allRooms()` and `adapter.clients()` again.

The production site uses about 300mb of memory with `Object.keys(io.nsps['/'].adapter.rooms)` and about 1.6gb and growing until the site crashes with `io.of('/').adapter.allRooms((err, rooms)=>{...`

**Comment by mayfer** [comment] 2017-06-15 02:04
@darrachequesne **Update:**

Mem leak seems to be gone after I updated the client side `socket.io-client.js` appropriately as well.
Will run it for a few days and see how it goes in production.

**Comment by darrachequesne** [comment] 2017-06-15 12:04
@mayfer great news! Please keep us updated.

**Comment by mayfer** [comment] 2017-06-15 18:12
@darrachequesne
All good still! Can confirm that this is solved. Thanks everyone!

**Comment by artofspeed** [comment] 2017-06-15 18:43
@mayfer does memory leak happen with updated client side, and old server side?

**Comment by mayfer** [comment] 2017-06-15 18:50
@artofspeed leak can be reproduced with older version of client side & newer version of server side.

**Closed** 2017-06-15 20:16 UTC

**Comment by fas3r** [comment] 2019-03-03 16:09
Hello @mayfer , @webeks , 

I know that the ticket is closed but you seems to deal with large number of connections and as i working on a new application based on socket io redis you might have some recommendations or maybe  answer few questions. 

Looking at the thread is seems that's better to avoid `allRooms`, so far I thought it could be good to leverage socket.io-redis and store the rooms/users connected in redis using a uset. 

To leverage a bit socket.io-redis I will also use redis streams with readgroup and use rxJs to listen directly on the socket.io-redis event. Doing that, I can easily store the messages in streams and emit across the different namespaces/rooms. 

I have a large network of clients (~10000) that would connect to the that server. I would like to know if it's possible to scale socket.io-redis across multiple instances  ? As long as the socket.io-redis server are connecting to the same redis-cluster will I still be able to communicate across the multiple nodes/namespaces/rooms across the different physical instance ? 

I created multiple namespace instead of using the default one ( '/' ), do you know if that's impact the performance ? 
At the post is quite old, what is your feedback since that time ? 

Thanks by advance.

**Comment by mayfer** [comment] 2019-03-05 23:30
Hi @fas3r 

Yes, it's a good idea to avoid allRooms and clients all together
We realized that every time these calls are made, the entire socket.io cluster generates a lot of chatter. All nodes are requested for which rooms/clients they are managing, which they respond to and the data is collected before returned.

If you want speedy retrieval of this information, you are highly advised to keep the rooms/clients in custom data structures in redis. Just set keys on socket init & delete on disconnect. This is how we solved our performance problems

10,000 clients with several socket.io nodes will work just fine

**Comment by ritikasib** [comment] 2020-07-29 07:09
@mayfer  Which version of socket-io.client did you you use for solving this memory leak issue ?

**Comment by artofspeed** [comment] 2023-08-11 11:51
> Again, storing the associations between ids and rooms in Redis is possible and should be (a lot) more efficient that the current version (where a node sends a request and wait for the response of all the other nodes), but there is still an issue about keeping data up-to-date when a node goes down / crashes / is restarted. Anyone has a suggestion?

@darrachequesne One idea is to store in Redis `socketId <-> serverId` and `socketId <-> roomId` mappings. Then periodically clean up stale mappings with [this method](https://stackoverflow.com/questions/7577923/redis-possible-to-expire-an-element-in-an-array-or-sorted-set) after a node crashes. Ofc, client needs to ping the server regularly to signal his socketIds are still valid. It can be added along in the [existing](https://socket.io/docs/v4/server-options/#pinginterval) `ping-pong` mechanism.

**Comment by darrachequesne** [comment] 2023-08-11 12:26
@artofspeed could you please explain your use case?
